public class ResumeWrapper {
    public message message;
	class message {
		public String full_name;	    //Chintamani R. Virulkar
		public String phone_number;	    //Not available
		public String email_id;	    //Not available
		public String year_of_experience;	    //3+ years
		public String prefered_location;	    //Pune, India
		public String role;	    //Senior Salesforce Developer
		public String professional_summary;	    //Experienced Senior Salesforce Developer with more than 3 years of experience in Pune, India.
		public List<String> primary_skills;
		public List<String> secondary_skills;
		public String highest_education;	    //Bachelor of Technology - BTech, Computer Science from Sandip University
	}

}